python3 rels.py disaster